### ISSUE TITLE
Can't make hyperrogue94n-src on ubuntu16.04

### ISSUE THREAD

**Issue by XzuRukneg** [zenorogue/hyperrogue#12]
Just follow instructions here  http://roguetemple.com/z/hyper/download.php
and copy the font file DejaVuSans-Bold.ttf, sound and music files from the Windows package in `hyperrogue94n-src/` folder. And try to make.
Output https://pastebin.com/NNGgRLAa

Incredible game, anyway!

**Comment by XzuRukneg** [comment]
Thank you for explanation! 
No sound the very first time, don't know why, but not important.
Very good version and amazing options! Nice job.
I got a hard bug (need session restart) by testing advanced option> 3D config, with "human to wall ratio". 

Rem: Maybe the 'sight range' can be increase more than 7?

**Comment by zenorogue** [comment]
The game is balanced around both you and the monsters having sight range of 7. However, the 'sight range' can be increased to more than 7 if you enable the cheat mode (I guess increasing this should be allowed in peace mode and tutorial too).

**Comment by XzuRukneg** [comment]
Ok, thanks.
 I also think an "easy mode" should make the game more accessible, for the non-addicted person.
(permanent death don't encourage to re-try many times)

**Comment by zenorogue** [comment]
A specific easy mode is not planned -- as other roguelikes, HyperRogue is more about the journey than the destination. The world is different each time, so that it should still be fun when trying again. [(A recent blogpost about this)](http://zenorogue.blogspot.com/2017/09/losing-is-fun.html)

You could try using the cheat mode, possibly placing some limit on the number of times you cheat (it is hard to determine what would be easy for whom), or the peaceful mode (for peaceful exploration and puzzle solving), or the Orb Strategy Mode (which is generally harder IMO, but it is easier in one aspect, namely that a single mistake is no longer deadly).
