### ISSUE TITLE
Why not use gettext to translate files?

### ISSUE THREAD

**Issue by nobrakal** [zenorogue/hyperrogue#3]
The langen util seems very advanced, and cans handle several language sensitivity.

But why not use one of the open source standard: gettext?

Gettext translates, strings per strings, and dynamically in languages defined each in a separated file. It:
- Allows practical languages switches (things more difficult to do with your proper translate tool)
- Facilitates translation. Many software are designed to edit and translate .po files. And files themselves are very simple to understand.
- Is a standard. Very simple to install and maintain.

Any thoughts?

**Comment by zenorogue** [comment]
Basically, I am annoyed with the low quality of (Polish) translations that I usually see, and I wanted HyperRogue's translation to be beautiful, not looking like something generated by a computer. For example, the message "You collect your first %1!" has only one form in English, but in Polish it has six different forms, depending on the player's genus (masculine or feminine) and the object's genus (masculine, feminine, or neuter); furthermore, %1 has to be given in accusative case here. Most software avoids the problem by assuming that the player is male, and using something ugly like "You collect you first treasure %1" (this makes the genus of "treasure" count, instead of %1). But I don't want that. Does gettext support cases and geni? In the gettext manual I only see that it supports plural forms of messages.

**Comment by nobrakal** [comment]
Hi,

Gettext doesn't seem to support cases and geni, but  I can't find any software who support it...
Between, I found the Context utility in gettext (see https://www.gnu.org/software/gettext/manual/html_node/Contexts.html ), who permit to handle such cases, I think. It allows multiple translation for the same word in english, with a given context.
Let's me quote:

"The gettext.h include file contains the lookup macros for strings with contexts. They are implemented as thin macros and inline functions over the functions from <libintl.h>.

const char *pgettext (const char *msgctxt, const char *msgid);

In a call of this macro, msgctxt and msgid must be string literals. The macro returns the translation of msgid, restricted to the context given by msgctxt. "

Does it seems to be usuable for you ? 

Sorry, but I'm french, and I'm not familiar with this problems...
