### ISSUE TITLE
Hypersian Rug "perspective" projection cannot be usefully rotated

### ISSUE THREAD

**Issue by qazedc** [zenorogue/hyperrogue#66]
Rotating the "rug" with the arrow keys in the Hypersian rug mode, when "perspective" projection is selected, just moves it out of view. Not very useful. I think the view should be always centered on the PC, as when the orthogonal projection is selected/

**Comment by zenorogue** [comment]
The idea of the "perspective" projection is that it gives you a first person perspective view of the model: you can put the camera at any point, and rotate it in any direction. Page Up/Page Down moves the camera to the front, not towards the model. (This is especially fun if you change the native geometry to spherical.)

You can rotate the model instead of the camera with Ctrl+arrows (this is explained in F1-help).
