### ISSUE TITLE
Game gets stuck in "expansion mode"

### ISSUE THREAD

**Issue by Quuxplusone** [zenorogue/hyperrogue#93]
When you die, the game shows you a random cool thing, such as your path through the map, or "expansion mode" (in which each visible cell is numbered with its distance from the player).

However, if you're seeing "expansion mode" and you click "restart" or "play the game!", you'll end up starting a new game _still in expansion mode_, so that the mouse movement doesn't work and every cell has a giant number superimposed on it.

I think starting a new game should clear the "expansion mode" toggle. (However, I do see that you can set `expansion mode=yes` in hyperrogue.ini; does that mean that someone might actually _want_ to play a whole game in that mode? I'm sure I don't have the full context.)

Edited to add: If you can show me a reliable way to get the game into expansion mode, I'll give a complete reproducer. Unfortunately the only ways I know to get into the mode are "edit hyperrogue.ini" and "keep dying until it happens randomly."

**Comment by zenorogue** [comment]
* Regarding reproducing: you can press ESC twice to see a new hint during the quit screen. The "expansion" hint requires that you are dead and at least 50 cells from the starting point.

* I think it was quite difficult to make it persist... you get two buttons "scroll" and "configure", and the default button "menu". If you press Esc the screen is disabled. You can also click "configure" then "disable". The one way where it persisted was when you clicked "menu" and then "restart the game". Even in that case, it would go away if you pressed Esc (because the quit screen is programmed to automatically disable visualizations it previously enabled). In 11.3a I have made it so that the main menu also disables the visualizations enabled in the quit screen.

* The saved config option is mostly because "it is weird to save this config but if you want, I won't stop you". (I could imagine some very weird use, though.) The normal way of enabling this visualization is: experiments with geometry -> size of the world. However, since it was not enabled by quit screen, it is also not automatically disabled by it. If somebody wants to see distances at all times, they probably want this to continue in new game too.

**Comment by Quuxplusone** [comment]
> In 11.3a I have made it so that the main menu also disables the visualizations enabled in the quit screen.

I'm not 100% sure, but I *think* this fixed it. This issue can be closed as far as I'm concerned.
