### ISSUE TITLE
Sandworm can path through hunting dogs

### ISSUE THREAD

**Issue by Quuxplusone** [zenorogue/hyperrogue#94]
If you lead a sandworm out of the Desert, it appears that it is able to path through some kinds of monsters — or at least through Hunting Dogs in their "guarding" phase.
![](https://i.imgur.com/tiiePGQ.png)
I think the sandworm should route around them as if they were ordinary monsters.

**Comment by zenorogue** [comment]
I cannot reproduce a Sandworm pathing through a hunting dog, and if it did, the dog would be eaten, instead of breaking the worm in half. 

One way this could happen is that for some reason the Sandworm decided to move through a not-yet-generated part of the map, and then a Dog was generated on top of it. Does this agree with your observations?

**Comment by Quuxplusone** [comment]
> One way this could happen is that for some reason the Sandworm decided to move through a not-yet-generated part of the map, and then a Dog was generated on top of it.

Yes, that's possible. In the screenshot, the worm was moving in a straight line, which in hindsight I find really strange — normally it follows the player. Maybe it had somehow decided that the player was unreachable (maybe I'd just been in the Land of Eternal Motion?) and started moving straight ahead in the absence of anything else to do.

I agree that it's not as easy to reproduce as I thought, and worms _do_ path correctly around dogs. So your explanation is worth pursuing.

**Comment by zenorogue** [comment]
I have made Sandworms generate the land around them as they go, hopefully this fixes this issue.
